### ISSUE TITLE
--status does not detect incomplete download on armv7

### ISSUE THREAD

**Issue by erikfleischer** [Sude-/lgogdownloader#54]
I have tried using my little [odroid-c1](http://archlinuxarm.org/platforms/armv7/amlogic/odroid-c1) for big downloads from gog. One of the downloads got interrupted and running 'lgogdownloader --status' does not detect the incomplete download.

The actual size as reported by ls:
```
$ ls -al
3532570624 Jun 21 21:48 gog_the_book_of_unwritten_tales_2_1.0.0.1.tar.gz
```

The content of the xml file provided by gog:
```
$ more gog_the_book_of_unwritten_tales_2_1.0.0.1.tar.gz.xml
<file name="gog_the_book_of_unwritten_tales_2_1.0.0.1.tar.gz" available="1" notavailablemsg="" md5="b899f85f6cf15fde0e80a08b0a1429
17" chunks="475" timestamp="2015-02-23 18:04:45" total_size="4973333114">
```

The output of --status:
```
$ lgogdownloader --status --game the_book_of_unwritten_tales_2_almanac_edition
OK the_book_of_unwritten_tales_2_almanac_edition gog_the_book_of_unwritten_tales_2_1.0.0.1.tar.gz 3532570624 b899f85f6cf15fde0e80a08b0a142917
```

So lgogdownloader does not detect the difference between the size of downloaded file and the total size as stated by the gog api.

This problem seems to be specific to either 32bit platforms or even the armv7 platform: If I move these files to a x64 box, the size difference is detected and the download resumed accordingly.

Tested against current master.
Platform:
odroid-c1 running ArchLinuxARM

**Comment by Sude-** [comment]
Hopefully 59faa40 fixes this issue
Downloader::checkStatus is a huge mess and has lots of duplicate code. I'll probably need to rewrite it later.

**Comment by erikfleischer** [comment]
I have tested your patch on my odroid-c1. Now I get this error message:

```
$ lgogdownloader --status --game the_book_of_unwritten_tales_2_almanac_edition
Getting game info 1 / 1
terminate called after throwing an instance of 'std::out_of_range'
  what():  stoi
```

**Comment by Sude-** [comment]
c4c2f8c should fix the std::out_of_range error

**Comment by erikfleischer** [comment]
Ok. The out_of_range error is gone. But ``--status`` still does not get it quite right:
```
$ lgogdownloader --status --game the_book_of_unwritten_tales_2_almanac_edition  ❯❯❯
Getting game info 1 / 1
MD5 the_book_of_unwritten_tales_2_almanac_edition gog_the_book_of_unwritten_tales_2_1.0.0.1.tar.gz 678365818 5c4dba9b5696e5deffcd0b3fe47e886b
```
It reports **678365818** as the file size. But the file in question is reported as **3532570624** size on disk by ``ls -al``.

So continuing the download does not work either.

**Comment by Sude-** [comment]
The reason it reports different file size is because I made it so that it reports the file size from xml data.
I changed it in 699c9f2 so that --status now reports the file size from disk rather than xml.

**Comment by erikfleischer** [comment]
Thanks for that fix. But I am not finished yet ;-)  - I have two more remarks on this topic
First: ``--status`` reported (before the last patch) 678365818 as file size - which does not make any sense because the total size as reported in the xml file is 4973333114 -- which looks to me like there is some kind of integer overflow going on.
Second: Although there is a size mismatch ``--status`` reports a MD5 mismatch - which does not make any sense for an incomplete file. I think it would be better to report an incomplete download.

To prove my point that there is some kind of overflow going on, this is what happens when actually try to download the game:
```
$ lgogdownloader --download --game the_book_of_unwritten_tales_2_almanac_edition                                              ❯❯❯
Getting game info 1 / 1
Downloading: Linux Installer, English
/home/erik/gog.com/the_book_of_unwritten_tales_2_almanac_edition/gog_the_book_of_unwritten_tales_2_1.0.0.1.tar.gz
  0% ▕                          ▏ 4096.00/4096.00MB @ 0.00kB/s ETA: 0s
Downloading: manual (extended, German, English)
/home/erik/gog.com/the_book_of_unwritten_tales_2_almanac_edition/extras/bout_2_almanac_manual.zip
  0% ▕                          ▏ 18.01/18.01MB @ 0.00kB/s ETA: 0s
```
So lgogdownloader just skips the first file an proceeds with the next one although the first file is not complete yet -- this might be a different issue - so let me know if I should open another issue.

**Comment by Sude-** [comment]
I added status code for file size mismatch in 64690d0

I guess the overflow happens with std::stoull at https://github.com/Sude-/lgogdownloader/blob/3f7fbc5/src/downloader.cpp#L2628 but I don't know why because unsigned long long should be large enough to hold the value. 
The standard says it should be at least 64 bits (http://en.cppreference.com/w/cpp/language/types)
_FILE_OFFSET_BITS=64 is defined in Makefile so size_t should also be 64 bits.

What file system are you using?
Because it stops at 4096MB it seems like the 4GB file size limit of FAT32.

**Comment by erikfleischer** [comment]
I am using ext4. So the maximum file size should not be a problem.

I have looked at [downloader.cpp](https://github.com/Sude-/lgogdownloader/blob/3f7fbc5/src/downloader.cpp#L2628) and added the following lines to the function ``void Downloader::checkStatus()``:
```
std::cout << "size_t:\t\t" << sizeof(size_t) << " bytes" << std::endl;
std::cout << "filesize:\t\t" << filesize << std::endl;
std::cout << "filesize_xml:\t\t" << filesize_xml << std::endl;
```
And here is the resulting output:
```
$ ./bin/Release/lgogdownloader --status --game the_book_of_unwritten_tales_2_almanac_edition                    ❯❯❯
size_t:         4 bytes
Getting game info 1 / 1
filesize:               3532570624
filesize_xml:           678365818
FS the_book_of_unwritten_tales_2_almanac_edition gog_the_book_of_unwritten_tales_2_1.0.0.1.tar.gz 3532570624 5c4dba9b5696e5deffcd0b3fe47e886b
```

**Comment by Sude-** [comment]
size_t is only 32 bits which causes the overflow (4973333114-2^32 = 678365818)

Does using off64_t instead of size_t help?
```
sed -e 's/std::size_t/off64_t/g' -e 's/size_t/off64_t/g' -i main.cpp src/*.cpp include/*.h
```

**Comment by erikfleischer** [comment]
I tried your sed patching -- it causes a lot of compile errors.

So I took a look at [boost:file_size](http://www.boost.org/doc/libs/1_46_0/libs/filesystem/v3/doc/reference.html#file_size). It specifies uintmax_t as a return type for the ``file_size()`` function. So what do you think of this little [patch](https://github.com/erikfleischer/lgogdownloader/commit/095492942ee4267309b94125a4f5ab4634fc227b) - replacing size_t for the filesize variables with uintmax_t?

**Comment by erikfleischer** [comment]
Quick info: I have extended my [patch](https://github.com/erikfleischer/lgogdownloader/commit/23df30d7be4fe85b43b2d3b0c5e7b8cba4e8b285). I hope I find some more time tomorrow to continue and test the changes.
